#!/usr/bin/env bash
# Script to ping an IP address 5 times with ping if the IP address is provided as an argument
if [ "$#" -ne 1 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping $1 -c 5
fi